"""Nombres de carpeta bajo OFICIOS a partir del remitente canónico (pestaña EMPRESAS)."""

# Destino físico histórico en Z:.../OFICIOS (sin punto final / alias cortos).
CARPETA_POR_EMPRESA = {
    "TELEFONICA DEL PERU S.A.A.": "TELEFONICA DEL PERU S.A.A",
    "AMERICA MOVIL PERU S.A.C.": "AMERICA MOVIL",
    "ENTEL PERU S.A.": "ENTEL PERU S.A",
    "WIGO S.A.": "WIGO S.A",
    "OPTICAL TECHNOLOGIES S.A.C.": "OPTICAL TECHNOLOGIES S.A.C",
    "DESARROLLOS TERRESTRES PERU S.A.": "DESARROLLOS TERRESTRES PERU S.A",
    "VIETTEL PERU S.A.C.": "VIETTEL PERU S.A.C",
    "GTD PERU S.A.": "GTD PERU S.A",
    "CENTURYLINK PERU S.A.": "CENTURYLINK PERU S.A",
    "TORRES UNIDAS DEL PERU S.R.L.": "TORRES UNIDAS DEL PERU S.R.L",
    "NEXTNET S.A.C.": "NEXTNET S.A.C",
    "INVERSIONES BALESIA S.A.C.": "INVERSIONES BALESIA S.A.C",
    "MEDIA COMMERCE PERU S.A.C.": "MEDIA COMMERCE PERU S.A.C",
    "AMERICATEL PERU S.A.": "AMERICATEL PERU S.A",
    "BTS TOWERS DE PERU S.A.C.": "BTS TOWERS DE PERU S.A.C",
    "BANTEL S.A.C.": "BANTEL S.A.C",
    "DESARROLLO DE INFRAESTRUCTURA DE TELECOMUNICACIONES": "DESARROLLO DE INFRAESTRUCTURA DE TELECOMUNICACIONES",
    "TELXIUS TORRES PERU S.A.C.": "TELXIUS TORRES PERU S.A.C",
    "TURRIS TELECOM DE PERU S.A.C.": "TURRIS TELECOM DE PERU S.A.C",
    "ATC SITIOS DEL PERU SOCIEDAD COMERCIAL DE RESPONSABILIDAD LIMITADA": (
        "ATC SITIOS DEL PERU SOCIEDAD COMERCIAL DE RESPONSABILIDAD LIMITADA"
    ),
    "PHOENIX TOWER INTERNATIONAL PERU S.A.C.": "PHOENIX TOWER INTERNATIONAL PERU S.A.C",
    "AWC PERU S.A.C.": "AWC PERU S.A.C",
    "FIBERTEL PERU S.A.": "FIBERTEL PERU S.A",
    "TELECOM BUSINESS SOLUTION S.R.L.": "TELECOM BUSINESS SOLUTION S.R.L",
    "G & S CONTRATISTAS GENERALES S.A.C.": "GS CONTRATISTAS",
    "INTERNEXA PERU S.A.": "INTERNEXA",
    "UFINET PERU S.A.C.": "UFINET PERU S.A.C",
    "YACHAY TELECOMUNICACIONES S.A.C.": "YACHAY TELECOMUNICACIONES S.A.C",
    "LELITV E.I.R.L.": "LELITIV",
    "MORE STEEL TOWERS S.A.C.": "MORE STEEL TOWERS S.A.C",
    "EMPRESA NACIONAL DE TELECOMUNICACIONES BOLIVIA S.A.C.": "EMPRESA NACIONAL DE TELECOMUNICACIONES",
    "SATELITAL TELECOMUNICACIONES S.A.C.": "SATELITAL TELECOMUNICACIONES S.A.C",
    "CELL SITE SOLUTIONS PERU S.A.C.": "CELL SITE SOLUTIONS",
    "COAR NORTH S.A.C.": "COAR NORTH S.A.C",
    "J.R. TELECOM S.R.LTDA.": "J.R. TELECOM S.R.LTDA",
    "JYS TOWERS E.I.R.L.": "JYS TOWERS",
    "SBA TORRES PERU S.A.": "SBA TORRES",
    "TELECOMMUNICATIONS PARTNERS S.A.C.": "TELECOMUNICATION PARTNERS",
    "ANC PERU S.A.C.": "ANC PERU S.A.C",
    "CATV. FULL IMAGEN S.A.C.": "CATV. FULL IMAGEN S.A.C",
    "CJ TELECOM S.A.C.": "CJ TELECOM S.A.C",
    "COBRA PERU S.A.": "COBRA PERU S.A",
    "INGENIERIA EN GESTION DE NEGOCIOS Y OPORTUNIDADES S.A.C.": (
        "INGENIERIA EN GESTION DE NEGOCIOS Y OPORTUNIDADES S.A.C"
    ),
    "NETLINE PERU S.A.": "NETLINE PERU S.A",
    "WG COMUNICACIONES DIGITALES S.A.C.": "WG COMUNICACIONES DIGITALES S.A.C",
}

ESTADOS_OFICIO = ("COMPLETO", "PARCIAL", "INCOMPLETO")


def nombre_carpeta_empresa(empresa: str) -> str:
    empresa = str(empresa or "").strip()
    if not empresa:
        return ""
    if empresa in CARPETA_POR_EMPRESA:
        return CARPETA_POR_EMPRESA[empresa]
    # Convención EVAP: quitar punto final del sufijo legal.
    return empresa.rstrip(".")
